### ISSUE TITLE
Add gitignore for Python

### ISSUE THREAD

**Issue by flyingcakes85** [EndeavourOS-Community-Editions/qtile#11]
Since qtile uses python, and there's a high chance contributors will open it in VSCode - there will be .pyc files in working directory created by VSCode's python extension. They are not meant to be committed, but often while doing `git add .` or similar, they will get committed, as in #10 

So adding a gitignore file will help prevent this. Also lift some work off of contributors.

These three lines should suffice for the pycache directory.
```
__pycache__/
*.py[cod]
*$py.class
```

A complete example can be found here : https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by codic12** [comment]
Thanks :smile:

**Comment by codic12** [comment]
Fixed!
