### ISSUE TITLE
__pycache__ folder should not be version controlled

### ISSUE THREAD

**Issue by tusqasi** [EndeavourOS-Community-Editions/qtile#15]
As far as I can tell, `__pycache__` folder should not be version controlled. It should be removed, maybe.

**Comment by tusqasi** [comment]
https://github.com/EndeavourOS-Community-Editions/qtile/tree/main/.config/qtile/modules/__pycache__

**Comment by flyingcakes85** [comment]
You're right, it shouldn't be here. Thanks for reporting. Should be fixed soon. :+1:

**Comment by codic12** [comment]
Fixed via latest commit.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/PKGBUILDS/commit/ebabd4ab327ad33f14d3a57241c337a114c57ce5

**Comment by flyingcakes85** [comment]
Guess I need to write a discord bot to remind codic whenever an update is required :wink:

**Comment by killajoe** [comment]
could be automatic altogether.. if it is only about updating pkgrel ;)
