### ISSUE TITLE
Change terminal to alacritty

### ISSUE THREAD

**Issue by adam4nj** [EndeavourOS-Community-Editions/qtile#16]
Does changing the default terminal from xfce4-terminal to alacritty break any dependencies?

**Comment by codic12** [comment]
It won't break anything, we need to just remove the xfce4-term conf and add the alacritty configuration. I see no reason for switching though; xfce4-terminal is what the other CEs use and it works dang well so I don't plan to switch any time soon. Thanks for asking!
