### ISSUE TITLE
Some packages not installed by default and missing files

### ISSUE THREAD

**Issue by yungParrot** [EndeavourOS-Community-Editions/qtile#17]
Hi, I've found two minor bugs.  
1. [Dunst is not being installed by default](https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/packages-repository.txt)
2. [Some icons are not installed by default, but are still referenced in .dunstrc](https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/.config/dunst/dunstrc#L296)  
```
➜ ~ dunst
WARNING: Setting geometry in section global doesn't exist
WARNING: Setting notification_height in section global doesn't exist
WARNING: Setting startup_notification in section global doesn't exist
WARNING: Setting verbosity in section global doesn't exist
WARNING: Section shortcuts is deprecated.
Acting on notifications has been moved to its own utility. For more information, see the manual for dunstctl.
Ignoring this section.
WARNING: Failed to load image info for /home/brodie/.config/dunst/critical.png
WARNING: No icon found in path: '/home/brodie/.config/dunst/critical.png'
```

Edit: I've also found another bug with `i3lock`, when running the `powermenu` script and choosing the lock option, [a script is supposed to run](https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/.config/rofi/powermenu.sh#L29)
yet it cannot be found inside the repository :cry:

**Comment by codic12** [comment]
Thanks. To be consistent with some other editions, I just changed i3lock to slock for now. The icons were from a PR and are now removed, and dunst has been added to the packages file. Don't know how I missed these, thanks! :sweat_smile:
