### ISSUE TITLE
Bugfix for qtile config

### ISSUE THREAD

**Issue by etrigan63** [EndeavourOS-Community-Editions/qtile#18]
There are a couple of bugs in the qtile config that ships with EOS. Here are the fixes:

Specifically:
in `modules/screens.py`:

`from modules.keys import terminal`

needs to be added for the `CheckUpdates` widget to be able to launch the updater upon clicking it.

and

in `modules/groups.py`:

`from libqtile.lazy import lazy`
needs to be
`from libqtile.command import lazy`
to correct a lookup loop.

**Comment by killajoe** [comment]
@codic12

**Comment by codic12** [comment]
Thanks! Can you submit a PR?

**Comment by etrigan63** [comment]
PR #19 and PR #20 submitted.

**Comment by codic12** [comment]
Thanks! Both merged.

**Comment by elParaguayo** [comment]
> `from libqtile.lazy import lazy` needs to be `from libqtile.command import lazy` to correct a lookup loop.

Qtile developer here - that's not right. Importing `lazy` from `libqtile.command` is deprecated, Importing from `libqtile.lazy` is correct (and is in our default configuration). If that doesn't work then you've got another issue somewhere.

**Comment by etrigan63** [comment]
The logs were full of lookup loops stating that it was caused by `from libqtile.lazy import lazy`. I am no longer on qtile so I cannot help anymore.

**Comment by codic12** [comment]
That's interesting, I will try to change it back later and check the logs.
