### ISSUE TITLE
Splitting qtile config can cause `reload_config` to fail

### ISSUE THREAD

**Issue by elParaguayo** [EndeavourOS-Community-Editions/qtile#21]
FYI we've seen some users reporting that configs fail to reload when the config file is split into multiple files (as you do here).

You can see the issue here: https://github.com/qtile/qtile/issues/3377

**Comment by codic12** [comment]
Thanks. I haven't yet experienced this issue, and I think it would be better to just hold out until a fix comes out (it comes quickly enough into arch repos ;) )

**Comment by cybardev** [comment]
Has this not been resolved by qtile/qtile#3396 already? If so, maybe it could be closed now.

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
