### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by ZizouHuweidi** [EndeavourOS-Community-Editions/qtile#22]
I got this error multiple times when trying to install EOS qtile edition

Command <i>pacman -Sy --needed --noconfirm - < /tmp/ce/qtile.txt</i> failed to finish in 600 seconds.
There was no output from the command.

**Comment by codic12** [comment]
Hi,

This doesn't look like an issue with the CE, but with the installer. I suspect that there is some issue with fetching the packages:
 - your internet is too slow
 - or there is some issue with gpg keys
 - or your internet dropped out
 - 
I think a better place to ask this would be the endeavouros forum. thanks!
