### ISSUE TITLE
battery check spams upower/dbus

### ISSUE THREAD

**Issue by octopoulpe** [EndeavourOS-Community-Editions/qtile#23]
I had high cpu usage on dbus and upowerd, and lots of NameOwnerChanged in `dbus-monitor --system` (~20/s). Commented out the main loop in `check_battery.sh` and everything was OK after a reboot.
I think the main loop is missing a else case with a proper wait but I'm not sure I understood the desired flow.

**Comment by flyingcakes85** [comment]
I'm wanting to rewrite the script and use acpi instead of manually reading files 🤔

**Comment by codic12** [comment]
Certainly the best solution is to do that. I'm not quite sure what the specific issue is - I didn't write this script but it was PR'ed in. however, an else case should indeed just fix / workaround the issue for now, so I committed that. feel free to try again.

**Comment by cybardev** [comment]
Would adding a `libqtile.widget.Battery` widget to the bar and using the `notify_below` parameter work instead of having these two scripts?

I could modify the scripts to use `acpi` but if it's already done by the WM, I don't see a point in repeating efforts.

**Comment by killajoe** [comment]
unmaintained needs contributors or maintainer
