### ISSUE TITLE
Battery script referencing file that doesn't exist

### ISSUE THREAD

**Issue by yungParrot** [EndeavourOS-Community-Editions/qtile#24]
In the `~/.config/qtile/scripts/check_battery.sh` file you're referencing a script called `~/.config/qtile/scripts/low_bat.sh` that doesn't exist in this repository.

The home directory then has a file called `.xsession-errors` that is filled with:
```
/home/username/.config/qtile/scripts/check_battery.sh: line 28: /home/username/.config/qtile/scripts/low_bat.sh: No such file or directory
```

:cowboy_hat_face:

**Comment by killajoe** [comment]
its here:
https://github.com/EndeavourOS-Community-Editions/qtile/blob/b2aa6abeae104dae3d8d68f3b40657fb491972e8/.config/qtile/scripts/check_battery.sh#L28

i am not sure if the script name changed or if there wa sa different script before .. will need @codic12 to check

**Comment by yungParrot** [comment]
@killajoe renaming the script in this line https://github.com/EndeavourOS-Community-Editions/qtile/blob/b2aa6abeae104dae3d8d68f3b40657fb491972e8/.config/qtile/scripts/check_battery.sh#L28 to `low_bat_notifier.sh` seems to have solved my problem

**Comment by codic12** [comment]
Thanks!
