### ISSUE TITLE
Dunst package is missing

### ISSUE THREAD

**Issue by huguesmp** [EndeavourOS-Community-Editions/qtile#25]
Hi,

First of all, thank you for this wonderful community edition!

I installed from the Apollo media and noticed that the `dunst` package was missing. I see it is mentionned in `package-repository.txt` so not sure what happened (I'm still new to arch and eos).

Not worth creating a second issue I believe, but the wallpaper set during install was the one for the Artemis release.

I should note, I used the `Nvidia` option to boot and install the system.

**Comment by killajoe** [comment]
independently from used ISO you will result in the same installed system .. and will get latest wallpaper :) 
And yes i see no dunst in the list here:
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/f5766b57fb76296f89b093acbf529e3cb4eb4c73/calamares/modules/packagechooser_ce.conf#L198

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/commit/322befc35a66a7a4dcb28fd58d62b4a5d1443053

**Comment by killajoe** [comment]
thanks for your contribution b.t.w.!

**Comment by huguesmp** [comment]
Happy to help in a small way 🙂

Thank you for all the hard work on Endeavour OS!
