### ISSUE TITLE
xcursor-neutral is moved to AUR

### ISSUE THREAD

**Issue by killajoe** [EndeavourOS-Community-Editions/qtile#30]
xcursor-neutral is moved to AUR please check configs, and submit PKGBUILD update.

**Comment by codic12** [comment]
uhh... i don't see where this package is mentioned or used anywhere ?

**Comment by killajoe** [comment]
i have fixed that already .. 
https://github.com/endeavouros-team/calamares/blob/ab31bd7fe07f7790118fffe87b26010e77f2094c/data/eos/modules/packagechooser_ce.conf#L248
was there in all editions.. 

https://github.com/endeavouros-team/calamares/commit/2c213b694c715d6da153cdb34bc362deb9fd3acf
