### ISSUE TITLE
Nerd Fonts 3.0 breaks some symbols

### ISSUE THREAD

**Issue by thingsiplay** [EndeavourOS-Community-Editions/qtile#31]
Recently Nerd Fonts 3.0 got released and there are changes in the path of some fonts. This breaks display of some symbols used in the default installation of Qtile edition for EndeavourOS. The fix is easy: Just replace certain symbols with different one. In example the unmodified script at [~/.config/rofi/powermenu.sh](https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/.config/rofi/powermenu.sh) affected and needs to be updated. And probably other places too. The website https://www.nerdfonts.com/cheat-sheet can be used to find alternative symbols.

**Comment by jwijenbergh** [comment]
Hey, qtile maintainer here, nice project! Just stopping by, https://github.com/loichyan/nerdfix is a good tool to automatically fix them

**Comment by thingsiplay** [comment]
Right, I can handle my own stuff. Just reported here, so the file powermenu.sh from this project with those icons gets fixed too. Otherwise everyone who installs EndeavourOS Qtile edition will have a broken shutdown menu and need to know why this is in order to fix themselves.

**Comment by jwijenbergh** [comment]
Only trying to help ;). See #32

**Comment by thingsiplay** [comment]
I just realized how the "tone" of my reply may have been misunderstood and wasn't meant in a toxic way. Just meant if I fix it myself, the repo would still not be fixed. Thank you for making the changes. I have a little question. If the changes from the repo makes it to official installer file, does this come as an update to the users too or do we need to change the powermenu.sh script our selfs on the system? Will the update make changes in file ~/.config/rofi/powermenu.sh? Again, please excuse the wording from my part.

**Comment by jwijenbergh** [comment]
No worries, I wasn't offended, it's hard to exactly know what anyone really means in GitHub comments. 

I am a maintainer for Qtile itself but not for this repo. So for any updating questions you'd have to ask the maintainers for this Qtile flavor. My gut feeling is 'no' the files won't update. So I guess you'd have to run the install script again after cloning the repo with a fix https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/setup.sh

Make sure to make backups first of course.
