### ISSUE TITLE
Lock screen command on `powermenu.sh` not working

### ISSUE THREAD

**Issue by jotas6** [EndeavourOS-Community-Editions/qtile#33]
Hello! Thank you very much for this great community edition. I have been using and enjoying it for some time now.

I recently noticed that nothing happens when clicking on "Lock" in the power menu. This bug can be reproduced with the following steps:

1. Open the power menu by clicking on the power symbol on the right of the bar
1. Select the "Lock" option

Looking at the `.config/rofi/powermenu.sh` file, I think that the problem is probably [here](https://github.com/EndeavourOS-Community-Editions/qtile/blob/main/.config/rofi/powermenu.sh#L27-L29), as it looks for `/home/$USER/.config/scripts/i3lock-fancy/i3lock-fancy.sh`, but the folder `/home/$USER/.config/scripts` does not exist on my machine.

I have an idea to solve this, but I wanted to ask you if it would be appropriate since I am not familiar with the project:

## Solution

Looking at the repository for the bspwm edition, the "Lock" points to `/home/$USER/.config/bspwm/scripts/i3lock-fancy/i3lock-fancy.sh`, and they have the `i3lock.fancy` folder there. I tried adding those files to `/home/$USER/.config/qtile/scripts/i3lock-fancy/i3lock-fancy.sh`, correcting the path on `powermenu.sh` and in `i3lock-fancy.sh` and it worked well.

Please let me know if this would be an acceptable solution. Would be happy to create a PR on it.

**Comment by killajoe** [comment]
https://github.com/EndeavourOS-Community-Editions/qtile#readme
Would be nice to see a pull request?

**Comment by jotas6** [comment]
Sorry for taking this long to reply. I have created #34 applying those changes
