### ISSUE TITLE
scratchpad crashes qtile

### ISSUE THREAD

**Issue by auralluring** [EndeavourOS-Community-Editions/qtile#36]
[forum post](https://forum.endeavouros.com/t/import-error-from-qtile/47819?u=auratheenby)
just after installing, qtile started not loading the fancy config that comes with and using the default one instead. the initial error here was solved by replacing `Scratchpad` with `ScratchPad` ([here](https://github.com/EndeavourOS-Community-Editions/qtile/blob/8f33b9426ec0cbddab55e2d436dc961c6e2becf3/.config/qtile/modules/groups.py#L1) and in the `groups` list). i assume the class was renamed in libqtile. it then started complaining that it couldn't find the key "dropdown" (not starting at all), and i haven't figured that one out yet.

i'm very much a newbie to qtile (though not python), so i'm going to just leave the scratchpad commented out until i've done some more tinkering and am more comfortable, but i'll come back.

**Comment by bananabr34d** [comment]
I was coming here to report the same issue.  After fixing the ScratchPad issue the "dropdown" key not found does break qtile.  To fix it I reverted this [commit](https://github.com/EndeavourOS-Community-Editions/qtile/commit/83bad84f7a676cab93c1ef63e4889c17d6858cee).

**Comment by killajoe** [comment]
A pull request could fix the setup files here.. 
There is no maintainer currently here, feel free to create a pull request i can merge it and if you are using this edition you could maintain it for a while too.
