### ISSUE TITLE
Missing error handing for setup.sh

### ISSUE THREAD

**Issue by danvisx** [EndeavourOS-Community-Editions/qtile#8]
Tried sudo bash setup.sh, accepted to delete some packages and the end message was done. It's not present at log-in for the user and I don't really know the issue.

"presuming that all dependencies already installed" is a very ambiguous message. Is "packages-repository.txt" the list of dependencies?

**Comment by codic12** [comment]
Yes, packages-repository.txt is the list of packages.

> Tried sudo bash setup.sh, accepted to delete some packages and the end message was done. It's not present at log-in for the user and I don't really know the issue.

I'm not quite sure what you mean - what exactly is the issue? There is no qtile available at login?

**Comment by danvisx** [comment]
Yes, it was on my side I guess. After a few reboots it appeared in the selector at log-in. I don't know why though.

Anyway, since it's barely reproducible, I'll just close it. Thanks.

**Comment by codic12** [comment]
Weird, but glad your issue was solved!
